# Generated by Django 4.0.3 on 2022-04-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wxuser',
            name='user_name',
            field=models.CharField(max_length=20, verbose_name='用户名'),
        ),
    ]
