# Generated by Django 3.2 on 2022-05-05 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_auto_20220505_1332'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listofquestion',
            name='question_id',
        ),
        migrations.RemoveField(
            model_name='wrongquestions',
            name='question_id',
        ),
        migrations.AddField(
            model_name='listofquestion',
            name='question',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='administrator.question', verbose_name='对应的问题'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wrongquestions',
            name='havedone',
            field=models.BooleanField(default=False, verbose_name='是否已经做过'),
        ),
        migrations.AddField(
            model_name='wrongquestions',
            name='question',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='administrator.question', verbose_name='对应的问题'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listofquestion',
            name='openid',
            field=models.CharField(max_length=50, verbose_name='用户的openid'),
        ),
        migrations.AlterField(
            model_name='wrongquestions',
            name='openid',
            field=models.CharField(max_length=50, verbose_name='用户的openid'),
        ),
    ]
