# Generated by Django 3.2 on 2022-05-09 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='done_question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=50, verbose_name='用户的openid')),
                ('question_id', models.IntegerField(verbose_name='对应题目id')),
                ('sub_questionid', models.IntegerField(verbose_name='对应小题目id')),
                ('option', models.CharField(max_length=50, verbose_name='用户选项')),
                ('sub_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.subquestion', verbose_name='对应的问题')),
            ],
        ),
    ]
