# Generated by Django 3.2 on 2022-05-09 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_auto_20220509_2359'),
        ('client', '0002_done_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='done_question',
            name='option',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=5, verbose_name='用户选项'),
        ),
        migrations.AlterField(
            model_name='done_question',
            name='sub_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.subquestion', verbose_name='对应的小题'),
        ),
        migrations.AlterUniqueTogether(
            name='wrongquestions',
            unique_together={('openid', 'question_id')},
        ),
    ]
