# Generated by Django 4.0.3 on 2022-04-21 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='题目id')),
                ('title', models.TextField(verbose_name='题目标题')),
                ('type', models.CharField(choices=[('choice_question', '选择'), ('cloze_question', '完形'), ('reading_question', '阅读')], default='choice_question', max_length=20, verbose_name='题目类型')),
                ('text', models.TextField(blank=True, null=True, verbose_name='文章')),
                ('sub_que_num', models.IntegerField(verbose_name='子问题数量')),
            ],
        ),
        migrations.CreateModel(
            name='SubQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='子问题id')),
                ('number', models.IntegerField(verbose_name='子问题题号')),
                ('stem', models.TextField(blank=True, null=True, verbose_name='子问题题干')),
                ('A', models.TextField()),
                ('B', models.TextField()),
                ('C', models.TextField()),
                ('D', models.TextField()),
                ('answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=5, verbose_name='答案')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.question', verbose_name='父问题的id')),
            ],
        ),
    ]
