# Generated by Django 3.2 on 2022-05-09 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminApproveSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='solution',
            name='approval',
            field=models.IntegerField(default=0, verbose_name='被管理员认可的次数'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='reports',
            field=models.IntegerField(default=0, verbose_name='举报数'),
        ),
        migrations.AddConstraint(
            model_name='solution',
            constraint=models.CheckConstraint(check=models.Q(approval__gte=0), name='check_approval'),
        ),
        migrations.AddField(
            model_name='adminapprovesolution',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='认可该题解的管理员'),
        ),
        migrations.AddField(
            model_name='adminapprovesolution',
            name='solution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.solution', verbose_name='被认可的题解'),
        ),
    ]
