# Generated by Django 3.2 on 2022-05-07 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='data',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='bad_solution',
        ),
        migrations.AddField(
            model_name='notice',
            name='time',
            field=models.DateTimeField(auto_now=True, verbose_name='公告更新的时间'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='content',
            field=models.TextField(default='welcome to NewBee English', verbose_name='公告内容'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('CHOICE_QUE_NAME', '选择'), ('CLOZE_QUE_NAME', '完形'), ('READING_QUE_NAME', '阅读')], default='CHOICE_QUE_NAME', max_length=20, verbose_name='题目类型'),
        ),
        migrations.CreateModel(
            name='OperationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('添加', '添加'), ('修改', '修改'), ('删除', '删除'), ('其他', '其他')], default='添加', max_length=20, verbose_name='操作类型')),
                ('description', models.TextField(verbose_name='操作描述')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='操作时间')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='进行此操作的管理员')),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
    ]
