# Generated by Django 3.2 on 2022-05-05 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now=True, verbose_name='创建日期')),
                ('content', models.TextField(verbose_name='公告内容')),
            ],
        ),
        migrations.AddField(
            model_name='solution',
            name='bad_solution',
            field=models.BooleanField(default=False, verbose_name='是否被举报过多'),
        ),
    ]
